[[main]]
name = "Topics"
pageRef = "topics"
weight = 20

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/Doubrixel"
weight = 40

[[main]]
identifier = "blog"
name = "Blog"
pageRef = "en"
weight = 10

[[footer]]
name = "Imprint"
pageRef = "about"
